{
 "title": "Carnivorous Greenhouse",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Alert Timeline", "type": "alertlist", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature_celsius{sensor_name=\"SHT31-D\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(humidity_percent{sensor_name=\"SHT31-D\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(temperature_celsius{sensor_name=\"SHT31-D\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(humidity_percent{sensor_name=\"SHT31-D\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plant Doctor",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"plant_doctor\"} | scope_name=\"root\""
    }
   ]
  },
  {
   "type": "volkovlabs-image-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "alias": "Random Walk",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://192.168.1.92:5000/api/image/base64",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}